apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: volume01
  volumes:
  - name: volume01
    emptyDir:
      sizeLimit: 500Mi